name: FIRST

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target Environment for Deployment'
        default: 'None'
        type: choice
        required: true
        options:
        - None
        - DEV-CI
        - SIT
        - UAT
        - STG
        - PROD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  test:
    name: Test
    needs: build
    if: ${{ github.event.inputs.targetEnv != 'None' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up test environment
        id: setup
        run: |
          if [ "${{ github.event.inputs.targetEnv }}" == "DEV-CI" ]; then
            echo "Workflow file: .github/workflows/2.yml"
            gh workflow run .github/workflows/2.yml -R ${{ github.repository }} -f MY_ENV2=123321 -f MY_ENV=aaabbb   
          elif [ "${{ github.event.inputs.targetEnv }}" == "SIT" ]; then
            echo "Workflow file: .github/workflows/3.yml"
            gh workflow run .github/workflows/3.yml -R ${{ github.repository }} -f MY_ENV2=123321 -f MY_ENV=aaabbb
          fi
      - name: Run workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo ${{  github.event.inputs.targetEnv  }}
          
          
  # while :
  #   do
  #     status=$(gh api "repos/${{ github.repository }}/actions/runs" --jq ".workflow_runs[] | select(.name == \"SECOND\") | .status")
  #     if [[ "$status" == "completed" ]]; then
  #       break
  #     fi
  #     sleep 10
  #   done 