name: FIRST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MY_ENV: 123
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  test:
    name: Test
    needs: build
    uses: ${{ if eq(env.MY_ENV, '123') }}./.github/workflows/2.yml@v1${{ endif }}
    with:
      python_test_versions: 3.7
    secrets:
      MY_ENV2: abc
