name: FIRST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MY_ENV: 123
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up test environment
        id: setup
        run: |
          if [ "${{ env.MY_ENV }}" == "123" ]; then
            echo "::set-output name=testScript::./.github/workflows/2.yml"
          else
            echo "::set-output name=testScript::./.github/workflows/3.yml"
          fi

      - name: Run test script
        uses: ${{ steps.setup.outputs.testScript }}
        with:
          python_test_versions: 3.7
        secrets:
            MY_ENV2: abc