name: FIRST

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target Environment for Deployment'
        default: 'None'
        type: choice
        required: true
        options:
        - None
        - DEV-CI
        - SIT
        - UAT
        - STG
        - PROD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  test1:
    if: ${{ inputs.targetEnv }} == 'SIT'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run SIT workflow
        uses: benc-uk/workflow-dispatch@v1 
        with:
          workflow: ./.github/workflows/2.yml
          MY_ENV2: value1

  test2:
    if: ${{ inputs.targetEnv }} != 'SIT'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run other workflows
        uses: ./.github/workflows/3.yml
