name: FIRST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MY_ENV: 123
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up test environment
        id: setup
        run: |
          if [ "${{ env.MY_ENV }}" == "123" ]; then
            echo "Workflow file: .github/workflows/2.yml"
            echo "::set-output name=workflowFile::.github/workflows/2.yml"
          else
            echo "Workflow file: .github/workflows/3.yml"
            echo "::set-output name=workflowFile::.github/workflows/3.yml"
          fi

      - name: Run workflow
        run: |
          echo ${{ env.MY_ENV }}
          workflowFile=${{ steps.setup.outputs.workflowFile }}
          gh workflow run $workflowFile -R ${{ github.repository }} -p MY_ENV2=abc
