name: FIRST

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target Environment for Deployment'
        default: 'None'
        type: choice
        required: true
        options:
        - None
        - DEV-CI
        - SIT
        - UAT
        - STG
        - PROD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  posrun:
    name: Test
    needs: build
    if: ${{ github.event.inputs.targetEnv != 'None' }}
    uses: ${{ if eq(github.event.inputs.targetEnv, 'DEV-CI') }}.github/workflows/2.yml${{ else if eq(github.event.inputs.targetEnv, 'SIT') }}.github/workflows/3.yml${{ endif }}@v1
    with:
      python_test_versions: 3.7
    env:
      MY_ENV2: ${{ github.event.inputs.targetEnv }}
      SFDX_AUTH_URL_SIT: ${{ secrets.SFDX_AUTH_URL_SIT || '' }}
      SFDXUSERNAME_SIT: ${{ secrets.SFDXUSERNAME_SIT || '' }}
      SFDX_AUTH_URL_UAT: ${{ secrets.SFDX_AUTH_URL_UAT || '' }}
      SFDXUSERNAME_UAT: ${{ secrets.SFDXUSERNAME_UAT || '' }}
      SFDX_AUTH_URL_STG: ${{ secrets.SFDX_AUTH_URL_STG || '' }}
      SFDXUSERNAME_STG: ${{ secrets.SFDXUSERNAME_STG || '' }}
      SFDX_AUTH_URL_PROD: ${{ secrets.SFDX_AUTH_URL_PROD || '' }}
      SFDXUSERNAME_PROD: ${{ secrets.SFDXUSERNAME_PROD || '' }}