name: FIRST

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target Environment for Deployment'
        default: 'None'
        type: choice
        required: true
        options:
        - None
        - DEV-CI
        - SIT
        - UAT
        - STG
        - PROD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up test environment
        id: setup
        run: |
          if [ "${{ github.event.inputs.targetEnv }}" == "SIT" ]; then
            echo "Workflow file: .github/workflows/2.yml"
            echo "::set-output name=workflowFile::.github/workflows/2.yml"
          else
            echo "Workflow file: .github/workflows/3.yml"
            echo "::set-output name=workflowFile::.github/workflows/3.yml"
          fi
      - name: Run workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo ${{  github.event.inputs.targetEnv  }}
          gh workflow run ${{ steps.setup.outputs.workflowFile }} -R ${{ github.repository }} -f MY_ENV2=123321    
          
  # while :
  #   do
  #     status=$(gh api "repos/${{ github.repository }}/actions/runs" --jq ".workflow_runs[] | select(.name == \"SECOND\") | .status")
  #     if [[ "$status" == "completed" ]]; then
  #       break
  #     fi
  #     sleep 10
  #   done 



  # test1:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run SIT workflow
  #       if: ${{ github.event.inputs.targetEnv }} == 'SIT'
  #       uses: benc-uk/workflow-dispatch@v1
  #       with:
  #         workflow: 2.yml
  #         token: ${{ secrets.GH_TOKEN }}
  #         inputs: '{"MY_ENV2": "value1"}'
        
  # test2:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run SIT workflow
  #       if: ${{ github.event.inputs.targetEnv }} != 'SIT'
  #       uses: benc-uk/workflow-dispatch@v1 
  #       with:
  #         workflow: 3.yml
  #         token: ${{ secrets.GH_TOKEN }}
        