name: FIRST

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target Environment for Deployment'
        default: 'None'
        type: choice
        required: true
        options:
        - None
        - DEV-CI
        - SIT
        - UAT
        - STG
        - PROD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run SIT workflow
        if: ${{ github.event.inputs.targetEnv }} == 'SIT'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 2.yml
          token: ${{ secrets.GH_TOKEN }}
          inputs: '{"MY_ENV2": "value1"}'
        
  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run SIT workflow
        if: ${{ github.event.inputs.targetEnv }} != 'SIT'
        uses: benc-uk/workflow-dispatch@v1 
        with:
          workflow: 3.yml
          token: ${{ secrets.GH_TOKEN }}
        