name: FIRST

on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target Environment for Deployment'
        default: 'None'
        type: choice
        required: true
        options:
        - None
        - DEV-CI
        - SIT
        - UAT
        - STG
        - PROD
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MY_ENV: 123
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up test environment
        id: setup
        run: |
          if [ "${{ inputs.targetEnv }}" == "SIT" ]; then
            echo "Workflow file: .github/workflows/2.yml"
            echo "::set-output name=workflowFile::.github/workflows/2.yml"
          else
            echo "Workflow file: .github/workflows/3.yml"
            echo "::set-output name=workflowFile::.github/workflows/3.yml"
          fi

      - name: Run workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo ${{ inputs.targetEnv }}
          workflowFile=${{ steps.setup.outputs.workflowFile }}
          gh workflow run $workflowFile -R ${{ github.repository }} -f MY_ENV2=abc
