# This is a basic workflow to help you get started with Actions

name: SECOND

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      python_test_versions:
        default: "['3.8']"
        required: false
        type: string
      MY_ENV:
        description: 'Input for my workflow'
        required: true
        type: string
        default: 'default value'
      MY_ENV2:
        description: 'Input for my workflow'
        required: true
        type: string
        default: 'default value'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ inputs.MY_ENV }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world from the second one!
          echo ${{ inputs.MY_ENV }}
          echo ${{ inputs.MY_ENV2 }}
          echo ${{ secrets.SECRET_TEST }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: sleep 10s