name: Scheduler

on:
  schedule:
    - cron: '*/3 * * * *' # A cada 10 minutos
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
      workflow:
        description: 'Workflow to retry (validation or deploy)'
        required: true

jobs:
  retry:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Retry pending workflows
      run: |
        PR_NUMBER=${{ github.event.inputs.pr_number }}
        WORKFLOW=${{ github.event.inputs.workflow }}
        
        # Obtenha todas as execuções de workflow em progresso
        ALL_WORKFLOWS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs?status=in_progress)
        echo "ALL_WORKFLOWS=${ALL_WORKFLOWS}"
        
        # Filtre as execuções de workflow que correspondem ao nome
        RUNNING_WORKFLOWS=$(echo $ALL_WORKFLOWS | jq -r '[.workflow_runs[] | select(.name == "Validation Pipeline" or .name == "Deploy Pipeline")] | length')
        
        # Imprima o número de execuções em andamento
        echo "RUNNING_WORKFLOWS=${RUNNING_WORKFLOWS}"
        
        if [ "$RUNNING_WORKFLOWS" -eq 0 ]; then
          if [ "$WORKFLOW" == "validation" ]; then
            echo "Re-triggering validation workflow for PR #${PR_NUMBER}"
            curl -s -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/validation.yml/dispatches \
              -d '{"ref":"main", "inputs":{"pr_number": "'${PR_NUMBER}'"}}'
          elif [ "$WORKFLOW" == "deploy" ]; then
            echo "Re-triggering deploy workflow for PR #${PR_NUMBER}"
            curl -s -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy-main.yml/dispatches \
              -d '{"ref":"main", "inputs":{"pr_number": "'${PR_NUMBER}'"}}'
          fi
        else
          echo "Workflows still in progress. Exiting..."
        fi

        