name: VALIDATION

# Workflow run name
run-name: Workflow run Validation

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    environment: CI
    # concurrency: 
    #   group: salesforce-pipeline
    #   cancel-in-progress: false
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Determine deploy group
        id: determine-group
        run: |
          # Define a lógica para determinar o grupo de deploy (deploy1, deploy2, deploy3)
          # Para simplificação, vamos supor que o grupo é determinado por uma variável de ambiente
          GROUP="deploy1"  # Substitua com a lógica adequada para determinar o grupo
          echo "GROUP=${GROUP}" >> $GITHUB_ENV

      - name: Check for running validation workflows in group
        id: check-workflow
        run: |
          GROUP=${{ env.GROUP }}
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          RUNNING_VALIDATIONS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs?status=in_progress \
              | jq -r --arg group "$GROUP" '[.workflow_runs[] | select(.name == "Validation Pipeline") | select(.head_branch == $group)] | length')
          if [ "$RUNNING_VALIDATIONS" -gt 0 ]; then
            echo "There is a validation workflow already running in group ${GROUP}. Exiting and re-triggering..."
            curl -s -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/scheduler.yml/dispatches \
              -d '{"ref":"main", "inputs":{"pr_number": "'${PR_NUMBER}'", "group": "'${GROUP}'", "workflow": "validation"}}'
            exit 0
          fi

      # Runs a set of commands using the runners shell
      - name: Sleep 60 seconds
        run: sleep 60s
