name: VALIDATION

# Workflow run name
run-name: Workflow run Validation

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run validation
        run: echo "This is a validation workflow triggered when a pull request is opened."

  test_execution:
    needs: installation_authenticate_deploy
    name: Test-Execution
    uses: ./.github/workflows/2.yml
    with:
      python_test_versions: 3.7