name: Salesforce Data Import Pipeline - DEVCI

run-name: Workflow run PR No - ${{ github.event.pull_request.number }} and PR title - ${{ github.event.pull_request.title }} by @${{ github.actor }}

on:
  pull_request:
    branches:
      - main

    types:
      - opened
      - labeled

    labels:
      - 'Deploy Again'

jobs:
  Salesforce-Data-Import:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the current repository with all branches
      - id: CheckoutRepo
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: create test files
        run: |
          mkdir src
          mkdir src/AAA__c
          mkdir src/AAA__c/logs
          mkdir src/AAA__c/source
          mkdir src/AAA__c/target
          touch src/AAA__c/logs/1.log
          touch src/AAA__c/source/1.log
          touch src/AAA__c/target/1.log

          mkdir src/BBB__c
          mkdir src/BBB__c/logs
          mkdir src/BBB__c/source
          mkdir src/BBB__c/target
          touch src/BBB__c/logs/1.log
          touch src/BBB__c/source/1.log
          touch src/BBB__c/target/1.log

      - name: check files created
        run: |
          ls -lRa
      
      # Check all modified folders and tar.gz the files if exist
      - name: Check all modified folders and tar.gz the files if exist
        id: compactFiles
        run: |
           cd src
           find . -mindepth 1 -maxdepth 1 -type d | while read -r folder; do
             echo "Processing folder: $folder"
             pwd
             ls -la
             cd "$folder"

             echo "Current directory: $(pwd)"
             echo "Listing files in current directory before SFDMU execution:"
             ls -la  

             OBJECT_NAME=$(basename "$folder")

             if [ -d "logs" ] || [ -d "source" ] [ -d "target" ]; then
               echo "Checking if logs, source or target files exist"
               tar -czf ../$OBJECT_NAME-logs.zip  logs source target
             else
               echo "No logs, source or target files found."
             fi

             cd ..

           done

      - name: list `./src/.tar.gz` files
        run: ls -lh ./src/*.tar.gz || echo "file not found"
   
      - name: Upload all .tar.gz files
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.run_id }}-tar-archives"
          path: "./src/*.tar.gz"



