name: Validation test v2.2

# Workflow run name
run-name: Workflow run PR No - ${{ github.event.pull_request.number }} and PR title - ${{ github.event.pull_request.title }} by @${{ github.actor }}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - "releases/${{ vars.CURRENT_RELEASE }}*"
    paths-ignore:
      - "**/README.md"

jobs:
  validate_pr:
    runs-on: ubuntu-latest
   
    steps:
      - name: test
        continue-on-error: true
        run: |
         
          echo ${{ vars.CURRENT_RELEASE }}

     