name: Validation Pipeline

# Workflow run name
run-name: Validation Pipeline

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    environment: CI
    # concurrency: 
    #   group: salesforce-pipeline
    #   cancel-in-progress: false
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check for running workflows
        id: check-workflow
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          
          # Obtenha todas as execuções de workflow em progresso
          ALL_WORKFLOWS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs?status=in_progress)
          echo "ALL_WORKFLOWS=${ALL_WORKFLOWS}"
          
          # Filtre as execuções de workflow que correspondem ao nome
          RUNNING_WORKFLOWS=$(echo $ALL_WORKFLOWS | jq -r '[.workflow_runs[] | select(.name == "Validation Pipeline" or .name == "Deploy Pipeline")] | length')
          
          # Imprima os valores filtrados
          echo "RUNNING_WORKFLOWS=${RUNNING_WORKFLOWS}"
          
          if [ "$RUNNING_WORKFLOWS" -gt 0 ]; then
            echo "There is a workflow already running. Exiting and re-triggering..."
            echo "retry" > result.txt
          else
            echo "no-retry" > result.txt
          fi
  
      - name: Run Salesforce Validation
        if: steps.check-workflow.outputs.result == 'no-retry'
        run: |
          echo "Running Salesforce Validation"
          sleep 60s
     
      - name: Re-trigger workflow
        if: steps.check-workflow.outputs.result == 'retry'
        run: |
          curl -s -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/scheduler.yml/dispatches \
            -d '{"ref":"main", "inputs":{"pr_number": "'${PR_NUMBER}'", "workflow": "validation"}}'
