name: VALIDATION

# Workflow run name
run-name: Workflow run Validation

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    env:
      API_VERSION: ${{ secrets.API_VERSION }}
      API_VERSION_DEVCI: ${{ secrets.API_VERSION_DEVCI }}
      XX_VERSION: ${{ secrets.XX_VERSION }}
    # container:
    #    image: leandrocbarbosaalt/public-ubuntu:latest

    steps:
      # Store Auth URL

      - name: Print API Version
        # with: # Set the secret as an input
        #   API_VERSION: ${{ secrets.API_VERSION }}
        # env:
        #   API_VERSION:  ${{ secrets.API_VERSION }}
        run: |
          echo ${{ env.API_VERSION }} 

      - name: Print API Version DevCI
        run: |
          echo ${{ env.API_VERSION_DEVCI }} 

      - name: Print XX Version
        run: |
          echo ${{ env.XX_VERSION }}


            
      # Install required OS packages
      # - name: Install OS dependencies
      #   run: |
      #     sudo apt-get clean -y
      #     sudo apt-get update -y
      #     sudo apt --only-upgrade install -y zip
      #     sudo apt --only-upgrade install -y curl
      #     sudo apt --only-upgrade install -y wget
      #     sudo apt install openjdk-8-jdk -y
      #     sudo apt --only-upgrade install jq -y
      #     sudo apt --only-upgrade install grep -y
      #     sudo apt autoremove -y

      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Run validation
      #   run: | 
      #        pwd
      #        whereis docker

      # - name: Run validation
      #   run: zip --version


  # test_execution:
  #   needs: validate_pr
  #   name: Test-Execution
  #   uses: ./.github/workflows/2.yml