name: VALIDATION

# Workflow run name
run-name: Workflow run Validation

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    environment: CI
    # concurrency: 
    #   group: salesforce-pipeline
    #   cancel-in-progress: false
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Check for running workflows
        id: check-workflow
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          RUNNING_WORKFLOWS=$(gh api repos/${{ github.repository }}/actions/runs -q '.workflow_runs[] | select(.status=="in_progress") | .id')
          if [ -n "$RUNNING_WORKFLOWS" ]; then
            echo "There is a workflow already running. Exiting..."
            gh api repos/${{ github.repository }}/actions/runs -F event_type="delayed-pr-${PR_NUMBER}"
            exit 0
          fi

      # Runs a set of commands using the runners shell
      - name: Sleep 60 seconds
        run: sleep 60s

     
      - name: Re-trigger workflow if needed
        if: ${{ steps.check-workflow.outputs.action == 'retry' }}
        run: |
          echo "Re-triggering workflow..."
          gh workflow run validation.yml
          