name: Validation Pipeline - test

# Workflow run name
run-name: Workflow run PR No - ${{ github.event.pull_request.number }} and PR title - ${{ github.event.pull_request.title }} by @${{ github.actor }}

on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    environment: CI
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    if: ((github.head_ref == '${{ vars.SOURCE_BRANCH_NAME }}') && (github.event_name == 'pull_request')) && contains('["Leandro-c-barbosa-alt"]', github.actor))
    steps:
      - name: Run Salesforce Validation
        run: |
          echo "Running Salesforce Validation"
     